name: xmSports

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 11 * * *'
  watch:
    types: started
  repository_dispatch:
    types: xmSports

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 'Start'
      run: |
        pip install requests
        python3 main.py
      env:
       XMYD_USER: ${{ secrets.XMYD_USER || github.event.client_payload.XMYD_USER }}
       XMYD_PASSWD: ${{ secrets.XMYD_PASSWD || github.event.client_payload.XMYD_PASSWD }}
       XMYD_STEP: ${{ secrets.XMYD_STEP || github.event.client_payload.XMYD_STEP }}
       PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN || github.event.client_payload.PUSH_PLUS_TOKEN }}
       PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER || github.event.client_payload.PUSH_PLUS_USER }}
       

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
